# Generated by Django 4.2.7 on 2024-01-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('med_id', models.AutoField(primary_key=True, serialize=False)),
                ('med_category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('phar_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Purchasing',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.customer')),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.medicines')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.customer')),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.medicines')),
                ('phar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.pharmacist')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.purchasing')),
            ],
        ),
    ]
