# Generated by Django 4.2.7 on 2024-01-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_add',
            field=models.CharField(default='Chilonzor Tumani,9A', max_length=90),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_email',
            field=models.EmailField(default='aziztukhtasinov0404@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_password',
            field=models.CharField(default='123456789', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='medicines',
            name='description',
            field=models.TextField(default='Something was someone'),
        ),
        migrations.AddField(
            model_name='medicines',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='admin_email',
            field=models.EmailField(default='atukhtasinov22@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='admin_password',
            field=models.CharField(default='njnwccn', max_length=70),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='contact_add',
            field=models.CharField(default='Chilonzor Tumani,9A', max_length=90),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='med_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
